[uwsgi]
chdir = /app
module = app:app

master = true
processes = 2
threads = 2
enable-threads = true

env = PYTHONPATH=/app/src
env = MODEL_PATH=/app/models/model.joblib
env = FEATURE_COLUMNS_PATH=/app/configs/feature_columns.json

socket = 0.0.0.0:3031
vacuum = true
die-on-term = true